name: dynamic_backend_bridge
description: A dynamic backend switcher for Flutter providing unified, generic Auth and Database bridges supporting Supabase Cloud and Self-Hosted Supabase.
version: 0.0.6
homepage: https://github.com/rudra-rahul71/dynamic_backend_bridge

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.16.0
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.3.1
  get_it: ^9.2.1
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1
  flutter_timezone: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
